<html>
    <head>
        <title>@yield('title')</title>
        @yield('asset')
    </head>
    <body>
        <aside>
            @yield('aside')
        </aside>
        <main>
            @yield('body')
        </main>
        <footer>
            @yield('footer')
        </footer>
    </body>
</html>